# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-16 13:21
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dataleufu', '0004_auto_20171008_0516'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'categor\xeda',
                'verbose_name_plural': 'categor\xedas',
            },
        ),
        migrations.CreateModel(
            name='Layer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='t\xedtulo')),
                ('type', models.IntegerField(choices=[(1, 'Interna'), (2, 'Externa')], default=(1, 'Interna'), verbose_name='tipo de capa')),
                ('url', models.URLField(blank=True, verbose_name='Url de la nube de almacenamiento')),
                ('color', models.CharField(max_length=20, verbose_name='color')),
                ('size', models.IntegerField(verbose_name='tama\xf1o en p\xedxeles')),
                ('visible', models.BooleanField(default=True, verbose_name='visible al inicio')),
                ('category', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='layers', to='places.Category', verbose_name='categor\xeda')),
            ],
            options={
                'verbose_name': 'capa',
                'verbose_name_plural': 'capas',
            },
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('description', models.CharField(help_text='m\xe1ximo 3000 caracteres', max_length=3000, verbose_name='descripci\xf3n')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creaci\xf3n')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='places', to='places.Category', verbose_name='categor\xeda')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='places', to='dataleufu.UserProfile')),
            ],
            options={
                'verbose_name': 'punto',
                'verbose_name_plural': 'puntos',
            },
        ),
        migrations.CreateModel(
            name='PlaceImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=b'')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='places.Place')),
            ],
        ),
    ]
