# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-27 17:31
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='t\xedtulo')),
                ('description', models.CharField(help_text='m\xe1ximo 3000 caracteres', max_length=3000, verbose_name='descripci\xf3n')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creaci\xf3n')),
                ('image', models.ImageField(blank=True, upload_to=b'')),
            ],
        ),
    ]
