# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-03 19:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_auto_20170901_0041'),
    ]

    operations = [
        migrations.CreateModel(
            name='Layer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='t\xedtulo')),
                ('type', models.IntegerField(choices=[(1, 'Interna'), (2, 'Externa')], default=(1, 'Interna'), verbose_name='tipo de capa')),
                ('url', models.URLField(blank=True, verbose_name='Url de la nube de almacenamiento')),
                ('color', models.CharField(max_length=20, verbose_name='color')),
                ('size', models.IntegerField(verbose_name='tama\xf1o en p\xedxeles')),
                ('visible', models.BooleanField(default=True, verbose_name='tama\xf1o en p\xedxeles')),
                ('category', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='layers', to='places.Category', verbose_name='categor\xeda')),
            ],
        ),
    ]
