# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-04 21:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_layer'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaceImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=b'')),
            ],
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'categor\xeda', 'verbose_name_plural': 'categor\xedas'},
        ),
        migrations.AlterModelOptions(
            name='layer',
            options={'verbose_name': 'capa', 'verbose_name_plural': 'capas'},
        ),
        migrations.AlterModelOptions(
            name='place',
            options={'verbose_name': 'punto', 'verbose_name_plural': 'puntos'},
        ),
        migrations.RemoveField(
            model_name='place',
            name='image',
        ),
        migrations.AlterField(
            model_name='layer',
            name='visible',
            field=models.BooleanField(default=True, verbose_name='visible al inicio'),
        ),
        migrations.AddField(
            model_name='placeimage',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='places.Place'),
        ),
    ]
