# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-08 16:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0004_auto_20171004_2114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='title',
        ),
    ]
