# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-07 17:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataleufu', '0002_auto_20171007_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usergroup',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=b''),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=b''),
        ),
    ]
